### ISSUE TITLE
不能在多个文件跳转

### ISSUE THREAD

**Issue by assemblyios** [everettjf/XBookmark#1]
不能在多个文件跳转

**Comment by everettjf** [comment]
@assemblyios 谢谢使用。
现在文件定位还是不太好用。
可以先点击另一个书签，再点击回这个书签。就可以切换了。
最近一直在看Xcode到处的类，还在研究。

**Comment by assemblyios** [comment]
哥们,哈哈,没想到你是国内的,https://github.com/merrickp/JumpMarks 参考一下这个,这个可以跳转

**Comment by everettjf** [comment]
多谢提供。我去看看。
之前一直找书签插件，没找到所以自己写了个。
没想到已经有这么好的了。

**Comment by everettjf** [comment]
Hello，问题已经解决了。
重新安装下试试。
版本改为0.2了。
