### ISSUE TITLE
设置书签快捷键，不选快捷键，关闭，xcode就永远启动不了，只有删除插件

### ISSUE THREAD

**Issue by megarzzy** [everettjf/XBookmark#10]
是要删除一个配置文件，但是不知道配置文件在哪。调试也未成功，只要出了这个问题，就永远崩溃了

**Comment by everettjf** [comment]
配置文件在：文稿-》XBookmark
也就是 /Users/username/Documents/XBookmark

这个bug，我尽快解决。多谢。

**Comment by everettjf** [comment]
@megarzzy 卸载后重新安装下。这个bug应该是fix了。
