### ISSUE TITLE
Suggestion: Texts instead of icons in "Show Bookmarks" window 

### ISSUE THREAD

**Issue by palaniraja** [everettjf/XBookmark#5]
Hi,

Thank you for the plugin. I have a small suggestion, I thought texts instead of icons in Show Bookmarks is easy from user discovery and icons of different style feel little odd.

**Comment by palaniraja** [comment]
Closing the issue.

Ref: https://github.com/everettjf/XBookmark/pull/6

**Comment by everettjf** [comment]
Yes, it is really. It's difficult to find that there is a button , ha ha.
